package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class AvailabilityException extends RuntimeException{

	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = -7383090375349418721L;

	public AvailabilityException(String s) {
		super(s);
	}
	
}
