package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidAppointmentException extends RuntimeException{

	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 5117650550162941388L;

	public InvalidAppointmentException(String s) {
		super(s);
	}
	
}
