package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidEmailException extends RuntimeException {

	/**
//	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = -4842527580759407320L;

	public InvalidEmailException(String s) {
        super(s);
    }
}
