package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidUserException extends RuntimeException {

    /**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 3527029044137260896L;

	public InvalidUserException(String s) {
        super(s);
    }
}
