package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidPasswordException extends RuntimeException{

	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 2358060080758405387L;
	
	public InvalidPasswordException(String s) {
        super(s);
    }
}
