package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidProfileException extends RuntimeException{

	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 6032035321083089779L;
	
	public InvalidProfileException (String s) {
		super(s);
	}
}
