package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidMessageException extends RuntimeException {

	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = -351101148084247953L;

	public InvalidMessageException(String s) {
        super(s);
    }
}
