package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidTimetableException extends RuntimeException{
	
	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = -5202257112972678750L;

	public InvalidTimetableException(String s) {
		super(s);
	}
	
}
