package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class InvalidSubjectException extends RuntimeException {
	
	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 8100417931647842436L;

	public InvalidSubjectException(String s) {
		super(s);
	}

}
