package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class NoTutorsForSubjectException extends RuntimeException {
	
	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 5528667854946950512L;

	public NoTutorsForSubjectException(String s) {
        super(s);
    }

}
