package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class PaymentStatusException extends RuntimeException {

	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 1337189760776802578L;

	public PaymentStatusException(String s) {
		super(s);
	}
	
}
