package ch.unibe.ese.Tutorfinder.controller.exceptions;

public class RoleException extends RuntimeException{

	/**
	 * Autogenerated serialVersion
	 */
	private static final long serialVersionUID = 5609602436908315795L;
	
	public RoleException(String s) {
		super(s);
	}

}
